apiVersion: v1
kind: Pod 
metadata:
  name: postgres-pod
  labels:
    name: postgresPod
    app: postgresApp
spec:
  containers:
  -name: postgresApp
   image: postgres:9.4
  ports:
  -containerPort: 5432