apiVersion: v1
kind: Service 
metadata:
  name: db
  labels:
    name: db-service	
    app: exampleApp
spec:
  ports:
  -port: 6379
   targetPort: 6379
  selector:
   name: postgresPod
   app: postgresApp