apiVersion: v1
kind: Pod 
metadata:
  name: result-pod
  labels:
    name: resultPod
    app: resultApp
spec:
  containers:
  -name: resultApp
   image: docker pull dockersamples/examplevotingapp_result
   ports:
   -containerPort: 80