apiVersion: v1
kind: Pod 
metadata:
  name: worker-pod
  labels:
    name: workerPod
    app: workerApp
spec:
  containers:
  -name: WorkerApp
   image: docker pull dockersamples/examplevotingapp_worker
  ports:
  -containerPort: 80